export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/drugs'
export const MAIN_ROUTE = '/'
export const DRUG_ROUTE = '/drug'